name: dl-big-proj
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - moviepy
  - ipykernel
  - pandas
  - opencv
  - torchaudio
  - torchvision
  - cudatoolkit
  - pytorch
  - matplotlib
  - av
  - jupyterlab
  - scikit-learn
  - pytorch-model-summary
